"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const prisma_1 = require("../generated/prisma");
const prisma = new prisma_1.PrismaClient();
const rdaData = [
    { nutrient: 'VITAMIN_A', ageGroup: '4-8', sex: null, value: 400, unit: 'µg' },
    { nutrient: 'VITAMIN_A', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 900, unit: 'µg' },
    { nutrient: 'VITAMIN_A', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 700, unit: 'µg' },
    { nutrient: 'VITAMIN_A', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 900, unit: 'µg' },
    { nutrient: 'VITAMIN_A', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 700, unit: 'µg' },
    { nutrient: 'VITAMIN_A', ageGroup: '71+', sex: prisma_1.Sex.MALE, value: 900, unit: 'µg' },
    { nutrient: 'VITAMIN_A', ageGroup: '71+', sex: prisma_1.Sex.FEMALE, value: 700, unit: 'µg' },
    { nutrient: 'VITAMIN_C', ageGroup: '4-8', sex: null, value: 25, unit: 'mg' },
    { nutrient: 'VITAMIN_C', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 75, unit: 'mg' },
    { nutrient: 'VITAMIN_C', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 65, unit: 'mg' },
    { nutrient: 'VITAMIN_C', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 90, unit: 'mg' },
    { nutrient: 'VITAMIN_C', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 75, unit: 'mg' },
    { nutrient: 'VITAMIN_C', ageGroup: '71+', sex: prisma_1.Sex.MALE, value: 90, unit: 'mg' },
    { nutrient: 'VITAMIN_C', ageGroup: '71+', sex: prisma_1.Sex.FEMALE, value: 75, unit: 'mg' },
    { nutrient: 'VITAMIN_D', ageGroup: '4-8', sex: null, value: 15, unit: 'µg' },
    { nutrient: 'VITAMIN_D', ageGroup: '14-18', sex: null, value: 15, unit: 'µg' },
    { nutrient: 'VITAMIN_D', ageGroup: '19-50', sex: null, value: 15, unit: 'µg' },
    { nutrient: 'VITAMIN_D', ageGroup: '71+', sex: null, value: 20, unit: 'µg' },
    { nutrient: 'VITAMIN_E', ageGroup: '4-8', sex: null, value: 7, unit: 'mg' },
    { nutrient: 'VITAMIN_E', ageGroup: '14-18', sex: null, value: 15, unit: 'mg' },
    { nutrient: 'VITAMIN_E', ageGroup: '19-50', sex: null, value: 15, unit: 'mg' },
    { nutrient: 'VITAMIN_E', ageGroup: '71+', sex: null, value: 15, unit: 'mg' },
    { nutrient: 'VITAMIN_K', ageGroup: '4-8', sex: null, value: 55, unit: 'µg' },
    { nutrient: 'VITAMIN_K', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 60, unit: 'µg' },
    { nutrient: 'VITAMIN_K', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 75, unit: 'µg' },
    { nutrient: 'VITAMIN_K', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 120, unit: 'µg' },
    { nutrient: 'VITAMIN_K', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 90, unit: 'µg' },
    { nutrient: 'VITAMIN_K', ageGroup: '71+', sex: prisma_1.Sex.MALE, value: 120, unit: 'µg' },
    { nutrient: 'VITAMIN_K', ageGroup: '71+', sex: prisma_1.Sex.FEMALE, value: 90, unit: 'µg' },
    { nutrient: 'VITAMIN_B1', ageGroup: '4-8', sex: null, value: 0.6, unit: 'mg' },
    { nutrient: 'VITAMIN_B1', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 1.2, unit: 'mg' },
    { nutrient: 'VITAMIN_B1', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 1.0, unit: 'mg' },
    { nutrient: 'VITAMIN_B1', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 1.2, unit: 'mg' },
    { nutrient: 'VITAMIN_B1', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 1.1, unit: 'mg' },
    { nutrient: 'VITAMIN_B1', ageGroup: '71+', sex: prisma_1.Sex.MALE, value: 1.2, unit: 'mg' },
    { nutrient: 'VITAMIN_B1', ageGroup: '71+', sex: prisma_1.Sex.FEMALE, value: 1.1, unit: 'mg' },
    { nutrient: 'VITAMIN_B2', ageGroup: '4-8', sex: null, value: 0.6, unit: 'mg' },
    { nutrient: 'VITAMIN_B2', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 1.3, unit: 'mg' },
    { nutrient: 'VITAMIN_B2', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 1.0, unit: 'mg' },
    { nutrient: 'VITAMIN_B2', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 1.3, unit: 'mg' },
    { nutrient: 'VITAMIN_B2', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 1.1, unit: 'mg' },
    { nutrient: 'VITAMIN_B2', ageGroup: '71+', sex: prisma_1.Sex.MALE, value: 1.3, unit: 'mg' },
    { nutrient: 'VITAMIN_B2', ageGroup: '71+', sex: prisma_1.Sex.FEMALE, value: 1.1, unit: 'mg' },
    { nutrient: 'VITAMIN_B3', ageGroup: '4-8', sex: null, value: 8, unit: 'mg' },
    { nutrient: 'VITAMIN_B3', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 16, unit: 'mg' },
    { nutrient: 'VITAMIN_B3', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 14, unit: 'mg' },
    { nutrient: 'VITAMIN_B3', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 16, unit: 'mg' },
    { nutrient: 'VITAMIN_B3', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 14, unit: 'mg' },
    { nutrient: 'VITAMIN_B3', ageGroup: '71+', sex: prisma_1.Sex.MALE, value: 16, unit: 'mg' },
    { nutrient: 'VITAMIN_B3', ageGroup: '71+', sex: prisma_1.Sex.FEMALE, value: 14, unit: 'mg' },
    { nutrient: 'VITAMIN_B6', ageGroup: '4-8', sex: null, value: 0.6, unit: 'mg' },
    { nutrient: 'VITAMIN_B6', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 1.3, unit: 'mg' },
    { nutrient: 'VITAMIN_B6', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 1.2, unit: 'mg' },
    { nutrient: 'VITAMIN_B6', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 1.3, unit: 'mg' },
    { nutrient: 'VITAMIN_B6', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 1.3, unit: 'mg' },
    { nutrient: 'VITAMIN_B6', ageGroup: '71+', sex: prisma_1.Sex.MALE, value: 1.7, unit: 'mg' },
    { nutrient: 'VITAMIN_B6', ageGroup: '71+', sex: prisma_1.Sex.FEMALE, value: 1.5, unit: 'mg' },
    { nutrient: 'VITAMIN_B9', ageGroup: '4-8', sex: null, value: 200, unit: 'µg' },
    { nutrient: 'VITAMIN_B9', ageGroup: '14-18', sex: null, value: 400, unit: 'µg' },
    { nutrient: 'VITAMIN_B9', ageGroup: '19-50', sex: null, value: 400, unit: 'µg' },
    { nutrient: 'VITAMIN_B9', ageGroup: '71+', sex: null, value: 400, unit: 'µg' },
    { nutrient: 'VITAMIN_B12', ageGroup: '4-8', sex: null, value: 1.2, unit: 'µg' },
    { nutrient: 'VITAMIN_B12', ageGroup: '14-18', sex: null, value: 1.8, unit: 'µg' },
    { nutrient: 'VITAMIN_B12', ageGroup: '19-50', sex: null, value: 2.4, unit: 'µg' },
    { nutrient: 'VITAMIN_B12', ageGroup: '71+', sex: null, value: 2.4, unit: 'µg' },
    { nutrient: 'VITAMIN_B5', ageGroup: '4-8', sex: null, value: 3, unit: 'mg' },
    { nutrient: 'VITAMIN_B5', ageGroup: '14-18', sex: null, value: 5, unit: 'mg' },
    { nutrient: 'VITAMIN_B5', ageGroup: '19-50', sex: null, value: 5, unit: 'mg' },
    { nutrient: 'VITAMIN_B5', ageGroup: '71+', sex: null, value: 5, unit: 'mg' },
    { nutrient: 'VITAMIN_B7', ageGroup: '4-8', sex: null, value: 12, unit: 'µg' },
    { nutrient: 'VITAMIN_B7', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 20, unit: 'µg' },
    { nutrient: 'VITAMIN_B7', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 25, unit: 'µg' },
    { nutrient: 'VITAMIN_B7', ageGroup: '19-50', sex: null, value: 30, unit: 'µg' },
    { nutrient: 'VITAMIN_B7', ageGroup: '71+', sex: null, value: 30, unit: 'µg' },
    { nutrient: 'CHOLINE', ageGroup: '4-8', sex: null, value: 250, unit: 'mg' },
    { nutrient: 'CHOLINE', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 550, unit: 'mg' },
    { nutrient: 'CHOLINE', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 400, unit: 'mg' },
    { nutrient: 'CHOLINE', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 550, unit: 'mg' },
    { nutrient: 'CHOLINE', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 425, unit: 'mg' },
    { nutrient: 'CHOLINE', ageGroup: '71+', sex: prisma_1.Sex.MALE, value: 550, unit: 'mg' },
    { nutrient: 'CHOLINE', ageGroup: '71+', sex: prisma_1.Sex.FEMALE, value: 425, unit: 'mg' },
    { nutrient: 'CALCIUM', ageGroup: '4-8', sex: null, value: 1000, unit: 'mg' },
    { nutrient: 'CALCIUM', ageGroup: '14-18', sex: null, value: 1300, unit: 'mg' },
    { nutrient: 'CALCIUM', ageGroup: '19-50', sex: null, value: 1000, unit: 'mg' },
    { nutrient: 'CALCIUM', ageGroup: '71+', sex: null, value: 1200, unit: 'mg' },
    { nutrient: 'CHLORIDE', ageGroup: '4-8', sex: null, value: 1900, unit: 'mg' },
    { nutrient: 'CHLORIDE', ageGroup: '14-18', sex: null, value: 2300, unit: 'mg' },
    { nutrient: 'CHLORIDE', ageGroup: '19-50', sex: null, value: 2300, unit: 'mg' },
    { nutrient: 'CHLORIDE', ageGroup: '71+', sex: null, value: 1800, unit: 'mg' },
    { nutrient: 'CHROMIUM', ageGroup: '4-8', sex: null, value: 15, unit: 'µg' },
    { nutrient: 'CHROMIUM', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 35, unit: 'µg' },
    { nutrient: 'CHROMIUM', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 24, unit: 'µg' },
    { nutrient: 'CHROMIUM', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 35, unit: 'µg' },
    { nutrient: 'CHROMIUM', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 25, unit: 'µg' },
    { nutrient: 'CHROMIUM', ageGroup: '71+', sex: prisma_1.Sex.MALE, value: 30, unit: 'µg' },
    { nutrient: 'CHROMIUM', ageGroup: '71+', sex: prisma_1.Sex.FEMALE, value: 20, unit: 'µg' },
    { nutrient: 'COPPER', ageGroup: '4-8', sex: null, value: 440, unit: 'µg' },
    { nutrient: 'COPPER', ageGroup: '14-18', sex: null, value: 890, unit: 'µg' },
    { nutrient: 'COPPER', ageGroup: '19-50', sex: null, value: 900, unit: 'µg' },
    { nutrient: 'COPPER', ageGroup: '71+', sex: null, value: 900, unit: 'µg' },
    { nutrient: 'FLUORIDE', ageGroup: '4-8', sex: null, value: 1, unit: 'mg' },
    { nutrient: 'FLUORIDE', ageGroup: '14-18', sex: null, value: 3, unit: 'mg' },
    { nutrient: 'FLUORIDE', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 4, unit: 'mg' },
    { nutrient: 'FLUORIDE', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 3, unit: 'mg' },
    { nutrient: 'FLUORIDE', ageGroup: '71+', sex: prisma_1.Sex.MALE, value: 4, unit: 'mg' },
    { nutrient: 'FLUORIDE', ageGroup: '71+', sex: prisma_1.Sex.FEMALE, value: 3, unit: 'mg' },
    { nutrient: 'IODINE', ageGroup: '4-8', sex: null, value: 90, unit: 'µg' },
    { nutrient: 'IODINE', ageGroup: '14-18', sex: null, value: 150, unit: 'µg' },
    { nutrient: 'IODINE', ageGroup: '19-50', sex: null, value: 150, unit: 'µg' },
    { nutrient: 'IODINE', ageGroup: '71+', sex: null, value: 150, unit: 'µg' },
    { nutrient: 'IRON', ageGroup: '4-8', sex: null, value: 10, unit: 'mg' },
    { nutrient: 'IRON', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 11, unit: 'mg' },
    { nutrient: 'IRON', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 15, unit: 'mg' },
    { nutrient: 'IRON', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 8, unit: 'mg' },
    { nutrient: 'IRON', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 18, unit: 'mg' },
    { nutrient: 'IRON', ageGroup: '71+', sex: null, value: 8, unit: 'mg' },
    { nutrient: 'MAGNESIUM', ageGroup: '4-8', sex: null, value: 130, unit: 'mg' },
    { nutrient: 'MAGNESIUM', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 410, unit: 'mg' },
    { nutrient: 'MAGNESIUM', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 360, unit: 'mg' },
    { nutrient: 'MAGNESIUM', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 420, unit: 'mg' },
    { nutrient: 'MAGNESIUM', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 320, unit: 'mg' },
    { nutrient: 'MAGNESIUM', ageGroup: '71+', sex: prisma_1.Sex.MALE, value: 420, unit: 'mg' },
    { nutrient: 'MAGNESIUM', ageGroup: '71+', sex: prisma_1.Sex.FEMALE, value: 320, unit: 'mg' },
    { nutrient: 'MANGANESE', ageGroup: '4-8', sex: null, value: 1.5, unit: 'mg' },
    { nutrient: 'MANGANESE', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 2.2, unit: 'mg' },
    { nutrient: 'MANGANESE', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 1.6, unit: 'mg' },
    { nutrient: 'MANGANESE', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 2.3, unit: 'mg' },
    { nutrient: 'MANGANESE', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 1.8, unit: 'mg' },
    { nutrient: 'MANGANESE', ageGroup: '71+', sex: prisma_1.Sex.MALE, value: 2.3, unit: 'mg' },
    { nutrient: 'MANGANESE', ageGroup: '71+', sex: prisma_1.Sex.FEMALE, value: 1.8, unit: 'mg' },
    { nutrient: 'MOLYBDENUM', ageGroup: '4-8', sex: null, value: 22, unit: 'µg' },
    { nutrient: 'MOLYBDENUM', ageGroup: '14-18', sex: null, value: 43, unit: 'µg' },
    { nutrient: 'MOLYBDENUM', ageGroup: '19-50', sex: null, value: 45, unit: 'µg' },
    { nutrient: 'MOLYBDENUM', ageGroup: '71+', sex: null, value: 45, unit: 'µg' },
    { nutrient: 'PHOSPHORUS', ageGroup: '4-8', sex: null, value: 500, unit: 'mg' },
    { nutrient: 'PHOSPHORUS', ageGroup: '14-18', sex: null, value: 1250, unit: 'mg' },
    { nutrient: 'PHOSPHORUS', ageGroup: '19-50', sex: null, value: 700, unit: 'mg' },
    { nutrient: 'PHOSPHORUS', ageGroup: '71+', sex: null, value: 700, unit: 'mg' },
    { nutrient: 'POTASSIUM', ageGroup: '4-8', sex: null, value: 2300, unit: 'mg' },
    { nutrient: 'POTASSIUM', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 3000, unit: 'mg' },
    { nutrient: 'POTASSIUM', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 2300, unit: 'mg' },
    { nutrient: 'POTASSIUM', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 3400, unit: 'mg' },
    { nutrient: 'POTASSIUM', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 2600, unit: 'mg' },
    { nutrient: 'POTASSIUM', ageGroup: '71+', sex: prisma_1.Sex.MALE, value: 3400, unit: 'mg' },
    { nutrient: 'POTASSIUM', ageGroup: '71+', sex: prisma_1.Sex.FEMALE, value: 2600, unit: 'mg' },
    { nutrient: 'SELENIUM', ageGroup: '4-8', sex: null, value: 30, unit: 'µg' },
    { nutrient: 'SELENIUM', ageGroup: '14-18', sex: null, value: 55, unit: 'µg' },
    { nutrient: 'SELENIUM', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 55, unit: 'µg' },
    { nutrient: 'SELENIUM', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 60, unit: 'µg' },
    { nutrient: 'SELENIUM', ageGroup: '71+', sex: null, value: 55, unit: 'µg' },
    { nutrient: 'ZINC', ageGroup: '4-8', sex: null, value: 5, unit: 'mg' },
    { nutrient: 'ZINC', ageGroup: '14-18', sex: prisma_1.Sex.MALE, value: 11, unit: 'mg' },
    { nutrient: 'ZINC', ageGroup: '14-18', sex: prisma_1.Sex.FEMALE, value: 9, unit: 'mg' },
    { nutrient: 'ZINC', ageGroup: '19-50', sex: prisma_1.Sex.MALE, value: 11, unit: 'mg' },
    { nutrient: 'ZINC', ageGroup: '19-50', sex: prisma_1.Sex.FEMALE, value: 8, unit: 'mg' },
    { nutrient: 'ZINC', ageGroup: '71+', sex: prisma_1.Sex.MALE, value: 11, unit: 'mg' },
    { nutrient: 'ZINC', ageGroup: '71+', sex: prisma_1.Sex.FEMALE, value: 8, unit: 'mg' },
];
async function main() {
    console.log(`Start seeding RDA...`);
    for (const rda of rdaData) {
        const existingRda = await prisma.recommendedDailyAllowance.findFirst({
            where: {
                nutrient: rda.nutrient,
                ageGroup: rda.ageGroup,
                sex: rda.sex,
            },
        });
        if (!existingRda) {
            await prisma.recommendedDailyAllowance.create({
                data: rda,
            });
            console.log(`Created RDA for ${rda.nutrient} (${rda.ageGroup}, ${rda.sex || 'N/A'})`);
        }
        else {
            console.log(`RDA for ${rda.nutrient} (${rda.ageGroup}, ${rda.sex || 'N/A'}) already exists. Skipping.`);
        }
    }
    console.log(`Seeding RDA finished.`);
}
main()
    .then(async () => {
    await prisma.$disconnect();
})
    .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
});
//# sourceMappingURL=seed-rda.js.map